name: river_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  dio: ^5.2.1+1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  go_router: ^8.0.2
  google_fonts: ^5.0.0
  random_name_generator: ^1.1.0
  uuid: ^3.0.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
